"""Write improved FcmPushReceiver.kt with FCM token auto-re-registration."""
import pathlib

out = pathlib.Path(
    "apps/android/app/src/main/java/com/youreyes/app/fcm/FcmPushReceiver.kt"
)
out.parent.mkdir(parents=True, exist_ok=True)

lines = [
    "package com.youreyes.app.fcm\n",
    "\n",
    "import android.content.Context\n",
    "import android.util.Log\n",
    "import com.google.firebase.messaging.FirebaseMessagingService\n",
    "import com.google.firebase.messaging.RemoteMessage\n",
    "import com.youreyes.app.data.AppDatabaseHelper\n",
    "import com.youreyes.app.dispatcher.CommandDispatcher\n",
    "import com.youreyes.app.network.DeviceApiClient\n",
    "import java.util.concurrent.Executors\n",
    "\n",
    "// FCM Push Receiver - entry point for commands pushed from the backend.\n",
    "// Backend sends DATA messages: request_id, user_id, device_id, action, params_json, base_url, bearer_token\n",
    "class FcmPushReceiver : FirebaseMessagingService() {\n",
    "\n",
    "    private val executor = Executors.newSingleThreadExecutor()\n",
    "\n",
    "    override fun onNewToken(token: String) {\n",
    '        Log.i(TAG, "New FCM token received - saving and re-registering")\n',
    "        val prefs = getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)\n",
    "        prefs.edit().putString(KEY_FCM_TOKEN, token).apply()\n",
    "        val savedUserId     = prefs.getString(KEY_USER_ID, null)\n",
    "        val savedDeviceId   = prefs.getString(KEY_DEVICE_ID, null)\n",
    "        val baseUrl         = prefs.getString(KEY_BASE_URL, null)\n",
    "        val bearerToken     = prefs.getString(KEY_BEARER_TOKEN, null)\n",
    "        if (savedUserId != null && savedDeviceId != null && baseUrl != null && bearerToken != null) {\n",
    "            executor.execute {\n",
    "                DeviceApiClient().register(\n",
    "                    userId      = savedUserId,\n",
    "                    deviceId    = savedDeviceId,\n",
    '                    platform    = "android",\n',
    "                    pushToken   = token,\n",
    "                    baseUrl     = baseUrl,\n",
    "                    bearerToken = bearerToken,\n",
    "                )\n",
    '                Log.i(TAG, "Re-registered with backend after token refresh")\n',
    "            }\n",
    "        }\n",
    "    }\n",
    "\n",
    "    override fun onMessageReceived(message: RemoteMessage) {\n",
    "        val data = message.data\n",
    '        Log.d(TAG, "FCM message received, keys=${data.keys}")\n',
    "\n",
    '        val requestId   = data["request_id"]   ?: return logMissing("request_id")\n',
    '        val userId      = data["user_id"]       ?: return logMissing("user_id")\n',
    '        val deviceId    = data["device_id"]     ?: return logMissing("device_id")\n',
    '        val action      = data["action"]        ?: return logMissing("action")\n',
    '        val paramsJson  = data["params_json"]   ?: "{}"\n',
    '        val baseUrl     = data["base_url"]\n',
    '        val bearerToken = data["bearer_token"]\n',
    "\n",
    "        val ctx: Context = applicationContext\n",
    "        executor.execute {\n",
    "            val dispatcher = CommandDispatcher(\n",
    "                dbHelper = AppDatabaseHelper(ctx),\n",
    "                context  = ctx,\n",
    "            )\n",
    "            val result = dispatcher.processPushCommand(\n",
    "                requestId   = requestId,\n",
    "                userId      = userId,\n",
    "                deviceId    = deviceId,\n",
    "                action      = action,\n",
    "                paramsJson  = paramsJson,\n",
    "                baseUrl     = baseUrl,\n",
    "                bearerToken = bearerToken,\n",
    "            )\n",
    '            Log.i(TAG, "Dispatch result for request: $result")\n',
    "        }\n",
    "    }\n",
    "\n",
    "    private fun logMissing(field: String) {\n",
    '        Log.w(TAG, "FCM message missing field: $field - ignoring")\n',
    "    }\n",
    "\n",
    "    companion object {\n",
    '        const val PREFS_NAME       = "appdemo_prefs"\n',
    '        const val KEY_FCM_TOKEN    = "fcm_token"\n',
    '        const val KEY_USER_ID      = "user_id"\n',
    '        const val KEY_DEVICE_ID    = "device_id"\n',
    '        const val KEY_BASE_URL     = "base_url"\n',
    '        const val KEY_BEARER_TOKEN = "bearer_token"\n',
    '        private const val TAG      = "FcmPushReceiver"\n',
    "    }\n",
    "}\n",
]

out.write_text("".join(lines), encoding="utf-8")
print(f"Written {out.stat().st_size} bytes to {out}")
